### ISSUE TITLE
install with local zip

### ISSUE THREAD

**Issue by sezbez** [magicdude4eva/docker-gunbot#3]
would be great  to have a dockerfile and instructions for installing with local zip as gunthar releases beta fixes more regularly on their telegram announcements channel. 

would this be possible? I've tried to get it going but have failed. (for example the zip they release may only contain gunthy-linux file as it's just an update of the exe.

**Comment by magicdude4eva** [comment]
Valid point - I have been using this for more than a year but forgot to update this. I have now added a separate `Dockerfile` which just does that - replace your local version with https://github.com/magicdude4eva/docker-gunbot/blob/main/Dockerfile.slipstream.local

**Comment by sezbez** [comment]
fantastic. would be cool to have basic step by step (update readme) i.e as you need to combine the new gunthy-linux file into the zip and override major release version i believe.

**Comment by magicdude4eva** [comment]
It is not that complicated and 3. in the readme:

> If you also want to use beta-releases, use the `Dockerfile.slipstream.local` instead and rename it to Dockerfile. This requires that you have the beta-release in the same folder as the `Dockerfile` named as `gunthy-linux.zip`.

**Comment by magicdude4eva** [comment]
I have adjusted the build and generally build now with the beta. You can replace the download URL with the beta URL via https://gunthy.org/downloads/
